### ISSUE TITLE
input value is allowing negative number.

### ISSUE THREAD

**Issue by mehulsatardekar** [srujandeshpande/dice-on-demand#10]
![Screenshot from 2020-11-06 13-52-42](https://user-images.githubusercontent.com/36101139/98343256-9204a480-2037-11eb-9e78-b9d95c260780.png)

we can prevent this issue by adding min and max attributes in input fields.

**Comment by srujandeshpande** [comment]
Yes, that certainly can be done!

**Comment by mehulsatardekar** [comment]
can i work on this issue?

**Comment by srujandeshpande** [comment]
Sure!

**Comment by mehulsatardekar** [comment]
hi @srujandeshpande can you check my pr and close this issue :smiley:

**Comment by srujandeshpande** [comment]
Closed by #11
